ALTER TABLE drafts
ALTER COLUMN status DROP DEFAULT;

ALTER TABLE drafts
ALTER COLUMN status TYPE VARCHAR(32)
USING status::TEXT;

DROP TYPE IF EXISTS draft_status;

ALTER TABLE drafts
ALTER COLUMN status SET DEFAULT 'PENDING';