-- V7: Add generated_at column to drafts table
-- Required by Draft entity (tracks when draft was generated by LLM pipeline)
ALTER TABLE drafts
    ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ;

-- Backfill existing drafts with created_at as generated_at
UPDATE drafts
SET generated_at = created_at
WHERE generated_at IS NULL;

-- Index for queries filtering by generation date
CREATE INDEX IF NOT EXISTS idx_drafts_generated_at ON drafts (generated_at DESC);
